---
abstract: "webagent which interacts with and retrieves data from\nNCBI's eUtils"
author:
  - 'cjfields <cjfields@bioperl.org>'
build_requires:
  Bio::Root::Test: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-EUtilities
requires:
  Bio::DB::GenericWebAgent: 0
  Bio::ParameterBaseI: 0
  Bio::Root::IO: 0
  Bio::Root::Root: 0
  Bio::Root::RootI: 0
  Data::Dumper: 0
  HTTP::Request: 0
  Text::Wrap: 0
  URI: 0
  XML::Simple: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Bio-EUtilities
  homepage: http://metacpan.org/release/Bio-EUtilities
  repository: git://github.com/bioperl/bio-eutilities.git
version: 1.71
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@CJFIELDS/@Filter/GatherDir'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@CJFIELDS/@Filter/PruneCruft'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@CJFIELDS/@Filter/ManifestSkip'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@CJFIELDS/@Filter/MetaYAML'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::License
      name: '@CJFIELDS/@Filter/License'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@CJFIELDS/@Filter/Readme'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@CJFIELDS/@Filter/ExtraTests'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@CJFIELDS/@Filter/ExecDir'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@CJFIELDS/@Filter/ShareDir'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@CJFIELDS/@Filter/Manifest'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@CJFIELDS/@Filter/TestRelease'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@CJFIELDS/@Filter/ConfirmRelease'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@CJFIELDS/@Filter/UploadToCPAN'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@CJFIELDS/ModuleBuild'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@CJFIELDS/NextRelease'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@CJFIELDS/MetaJSON'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@CJFIELDS/OurPkgVersion'
      version: 0.003002
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@CJFIELDS/MetaConfig'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@CJFIELDS/Test::Compile'
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@CJFIELDS/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@CJFIELDS/PodSyntaxTests'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@CJFIELDS/MetaResources'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@CJFIELDS/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@CJFIELDS/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@CJFIELDS/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300006
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300006
x_authority: cpan:CJFIELDS
